server:
  port: 8020
  # 应用名称-服务名称
spring:
  application:
    name: order-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        discovery:
          username: nacos
          password: nacos
          namespace: public
